### PR TITLE
add diskCache and diskCachePath options

### PR DESCRIPTION
**Pull request by efernandesng**
Permites enable disk cache and define files location

### CODE REVIEW

**Comment by awlayton** [comment]
Looks pretty good, but could you add a simple test case? You could just enable the cache and set a file path, and then check that the file is created or something.

**Comment by efernandesng** [comment]
Done :)

The `diskCachePath` is only supported on phantomjs (>2.0). To test only diskCache, we need to know where is phantom instance default cache path. You know some easier way?

By now, I skipped the test on phantomjs 1.x.

**Comment by awlayton** [comment]
I do not know of an easier way. What you did is probably good enough.

**Comment by efernandesng** [comment]
ok, thanks!

**Pull request merged**
