### PR TITLE
Access page.plainText of the Phantom page object.

### PR DESCRIPTION
**Pull request by mzhangARS**
http://phantomjs.org/api/webpage/property/plain-text.html

### CODE REVIEW

**Comment by awlayton** [comment]
Seems reasonable. Could you add a test for it and add it to the Readme @mzhangARS? Thanks.

**Comment by mzhangARS** [comment]
Updated!

**Comment by awlayton** [comment]
The test needs to make sure what is returned by `.plainText()` *exactly* matches the contents of the file loaded. Your test does not do this.

**Comment by mzhangARS** [comment]
Ah, ok. I'll try again.

**Comment by mzhangARS** [comment]
@awlayton I've found that on my local machine, PhantomJS thinks there are 4 spaces between "This is my code." and "Next Page", but on Travis-CI, there are only 3. I'm using PhantomJS 2 locally, but all the PhantomJS 2 tests on Travis-CI failed. Do you know what might be causing this discrepancy?

**Comment by awlayton** [comment]
Perhaps add a test file that has just one block of text and then another tag with no text (e.g., a `<p>` with a sentence in it and an `<input>` or something). Then the plainText should *always* just be that exact sentence.

**Comment by mzhangARS** [comment]
Alright updated! 😄

**Comment by awlayton** [comment]
Looks good @mzhangARS. Thanks for contributing, and for putting up with my pickiness.

**Pull request merged**
