### PR TITLE
Check if __horseman exists on window object in browser before evaluate

### PR DESCRIPTION
**Pull request by robertpallas**
Fixing "ReferenceError: Can't find variable: __horseman".

Fairly complex Hapi.js API communicating with various websites via Horseman depending on user actions. The issue pops up because [window.__horseman init](https://github.com/johntitus/node-horseman/blob/e79acde57fc122000ea87bd08c78ff06d65534f9/lib/index.js#L367) does not run as the API answers to users killing the promise chain before it reaches this init. On subsequent actions with same Horseman instance running evaluate does not find the [__horseman](https://github.com/johntitus/node-horseman/blob/e79acde57fc122000ea87bd08c78ff06d65534f9/lib/actions.js#L841) in browser and the whole process fails.

Possibly better future solutions could be @awlayton [TODO: Consolidate into one page.evaluate?](https://github.com/johntitus/node-horseman/blame/e79acde57fc122000ea87bd08c78ff06d65534f9/lib/index.js#L271) and not adding the window.__horseman before we need it (only in evaluate).

Thanks!

### CODE REVIEW

**Comment by awlayton** [comment]
If `_horseman` isn't there, something went wrong. I do not think this change is a good idea. It just masks the real problem rather than fixing it.

**Comment by robertpallas** [comment]
I am yet to be able to isolate the issue into a simple example but working on it. What makes it tricky is that I cant reliably recreate it and did not always happen on live systems either. Only thing certain is that after adding the lines in this PR the issue is gone for me. I definitely want to be in sync with the project and not run my custom version in the long run.

Is there a reason why init of `__horseman` is where it is right now and not within evaluate only when its called? [window.__horseman init](https://github.com/johntitus/node-horseman/blob/e79acde57fc122000ea87bd08c78ff06d65534f9/lib/index.js#L367).

**Comment by robertpallas** [comment]
Did some tests and log mining and core of the issue seams to be that `phantomjs onLoadFinished triggered` is not always there. The reasons are still unknown and simple recreation fails.

**Comment by awlayton** [comment]
I guess we could move it like you want. But that won't fix the underlying problem. Right now it is part of the page setup. Your fix won't make the rest of the page setup happen as it should (e.g. injecting jQuery).

I do not know of a way to force the onLoadFinished, but even if there is one we need to know if loading it's actually finished or not somehow...

**Comment by awlayton** [comment]
The way it is now, it is*supposed* to wait for that callback before moving on to something else, e.g. an evaluate. Could you post some log of when it seems to not be waiting? Please turn on `DEBUG='horseman*'` and `BLUEBIRD_DEBUG=1` when generating the log.

**Comment by aryeharmon** [comment]
```
{ line: 2,
  message: 'Can\'t find variable: __horseman',
  sourceId: 139775304784960,
  stack: 'ReferenceError: Can\'t find variable: __horseman\n    at waitForCb (:2)\n    at evaluatePage (phantomjs://webpage.evaluate():6)\n    at phantomjs://webpage.evaluate():11\n    at phantomjs://webpage.evaluate():11\n    at /opt/netbet/node_modules/node-horseman/lib/actions.js:992:36\n    at tryCatcher (/opt/netbet/node_modules/bluebird/js/release/util.js:16:23)\n    at Function.Promise.fromNode.Promise.fromCallback (/opt/netbet/node_modules/bluebird/js/release/promise.js:178:30)\n    at Horseman.<anonymous> (/opt/netbet/node_modules/node-horseman/lib/actions.js:990:29)\n    at Horseman.tryCatcher (/opt/netbet/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/opt/netbet/node_modules/bluebird/js/release/promise.js:504:31)\n    at Promise._settlePromise (/opt/netbet/node_modules/bluebird/js/release/promise.js:561:18)\n    at Promise._settlePromiseCtx (/opt/netbet/node_modules/bluebird/js/release/promise.js:598:10)\n    at Async._drainQueue (/opt/netbet/node_modules/bluebird/js/release/async.js:143:12)\n    at Async._drainQueues (/opt/netbet/node_modules/bluebird/js/release/async.js:148:10)\n    at Immediate.Async.drainQueues [as _onImmediate] (/opt/netbet/node_modules/bluebird/js/release/async.js:17:14)\n    at processImmediate [as _immediateCallback] (timers.js:383:17)',

```

this happens when i use ignoreSSLErrors = true

**Comment by awlayton** [comment]
That is very interesting if it is related to `ignoreSLLErrors`. Could you please post a complete log of the output @aryeharmon (with `BLUEBIRD_DEBUG=1` and `DEBUG='horseman*'` set if they are not already)?

**Comment by jimthedev** [comment]
I am also getting this error. @awlayton here is a full error log with debugging enabled.

```
DEBUG='horseman*' BLUEBIRD_DEBUG=1 node ./as-library.js
module.js:341
    throw err;
    ^

Error: Cannot find module '/Users/jim.cummins/projects/tiyo-login/node_modules/node-horseman/lib/as-library.js'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:148:18)
    at node.js:405:3
➜  lib git:(horsemanjs) ✗ cd ../..
➜  node_modules git:(horsemanjs) ✗ cd ..
➜  tiyo-login git:(horsemanjs) ✗ DEBUG='horseman*' BLUEBIRD_DEBUG=1 node ./as-library.js
module.js:341
    throw err;
    ^

Error: Cannot find module '/Users/jim.cummins/projects/tiyo-login/as-library.js'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:148:18)
    at node.js:405:3
➜  tiyo-login git:(horsemanjs) ✗ cd examples 
➜  examples git:(horsemanjs) ✗ DEBUG='horseman*' BLUEBIRD_DEBUG=1 node ./as-library.js
  horseman using PhantomJS from phantomjs module +0ms
  horseman .setup() creating phantom instance 1 +5ms
  horseman .viewport() set +18ms 3200 1800
  horseman phantom created +506ms
  horseman phantom version 2.1.1 +37ms
  horseman page created +25ms
  horseman phantomjs onLoadFinished triggered +18ms success NaN
  horseman injected jQuery +50ms
  horseman .open() +21ms https://online.theironyard.com/users/sign_in
  horseman phantomjs onLoadFinished triggered +9s success 1
  horseman injected jQuery +24ms
  horseman .click() +1ms #new_user [type=submit]
  horseman .click() done +15ms
  horseman .waitForSelector() +1ms .dashboard
  horseman .waitFor() +1ms elementPresent .dashboard
  horseman:verbose .waitFor() iteration +87ms elementPresent false 56 1
  horseman:verbose .waitFor() iteration +48ms elementPresent false 116 1
  horseman:verbose .waitFor() iteration +54ms elementPresent false 177 1
  horseman:verbose .waitFor() iteration +48ms elementPresent false 230 1
  horseman:verbose .waitFor() iteration +77ms elementPresent false 285 1
  horseman:verbose .waitFor() iteration +43ms elementPresent false 344 1
  horseman:verbose .waitFor() iteration +50ms elementPresent false 398 1
  horseman:verbose .waitFor() iteration +65ms elementPresent false 449 1
  horseman:verbose .waitFor() iteration +44ms elementPresent false 506 1
  horseman:verbose .waitFor() iteration +54ms elementPresent false 559 1
  horseman:verbose .waitFor() iteration +53ms elementPresent false 611 1
  horseman:verbose .waitFor() iteration +62ms elementPresent false 661 1
  horseman:verbose .waitFor() iteration +38ms elementPresent false 714 1
  horseman:verbose .waitFor() iteration +55ms elementPresent false 766 1
  horseman:verbose .waitFor() iteration +56ms elementPresent false 819 1
  horseman:verbose .waitFor() iteration +43ms elementPresent false 870 1
  horseman:verbose .waitFor() iteration +50ms elementPresent false 921 1
  horseman:verbose .waitFor() iteration +68ms elementPresent false 979 1
  horseman:verbose .waitFor() iteration +49ms elementPresent false 1037 1
  horseman:verbose .waitFor() iteration +52ms elementPresent false 1088 1
  horseman:verbose .waitFor() iteration +118ms elementPresent true 1138 1
  horseman .waitFor() completed successfully +0ms
  horseman .waitForSelector() complete +1ms
  horseman .screenshot() +1ms big.png
  horseman:verbose .waitFor() iteration +43ms elementPresent true 1189 1
  horseman .waitFor() completed successfully +4ms
  horseman .evaluate() +3s <anonymous>
  horseman:verbose onError +93ms ReferenceError: Can't find variable: __horseman
        undefined: 2 in evaluate
        : 74 in <anonymous> 1
  horseman:verbose .evaluate() waiting for callback +0ms <anonymous> null 1
  horseman .waitFor() +0ms waitForCb
Warning: a promise was rejected with a non-error: [object Object]
    at /Users/jim.cummins/projects/tiyo-login/node_modules/node-horseman/lib/actions.js:1010:30
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)
From previous event:
    at handleErrback (/Users/jim.cummins/projects/tiyo-login/node_modules/node-horseman/lib/actions.js:1003:23)
    at /Users/jim.cummins/projects/tiyo-login/node_modules/node-phantom-simple/node-phantom-simple.js:60:18
    at IncomingMessage.<anonymous> (/Users/jim.cummins/projects/tiyo-login/node_modules/node-phantom-simple/node-phantom-simple.js:645:9)
    at emitNone (events.js:85:20)
    at IncomingMessage.emit (events.js:179:7)
    at endReadableNT (_stream_readable.js:913:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
From previous event:
    at Horseman.<anonymous> (/Users/jim.cummins/projects/tiyo-login/node_modules/node-horseman/lib/actions.js:1002:5)
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)
From previous event:
    at Horseman.evaluatePage (/Users/jim.cummins/projects/tiyo-login/node_modules/node-horseman/lib/actions.js:984:20)
    at Timeout.waitForCheck [as _repeat] (/Users/jim.cummins/projects/tiyo-login/node_modules/node-horseman/lib/actions.js:1646:26)
    at Timeout.wrapper [as _onTimeout] (timers.js:408:11)
    at tryOnTimeout (timers.js:224:11)
    at Timer.listOnTimeout (timers.js:198:5)

Warning: a promise was rejected with a non-error: [object Object]
    at Horseman.<anonymous> (/Users/jim.cummins/projects/tiyo-login/node_modules/node-horseman/lib/actions.js:1664:8)
From previous event:
    at Horseman.<anonymous> (/Users/jim.cummins/projects/tiyo-login/node_modules/node-horseman/lib/actions.js:1632:10)
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)
From previous event:
    at Horseman.waitForPage (/Users/jim.cummins/projects/tiyo-login/node_modules/node-horseman/lib/actions.js:1631:20)
    at waitForCb (/Users/jim.cummins/projects/tiyo-login/node_modules/node-horseman/lib/actions.js:918:25)
    at /Users/jim.cummins/projects/tiyo-login/node_modules/node-phantom-simple/node-phantom-simple.js:60:18
    at IncomingMessage.<anonymous> (/Users/jim.cummins/projects/tiyo-login/node_modules/node-phantom-simple/node-phantom-simple.js:645:9)
    at emitNone (events.js:85:20)
    at IncomingMessage.emit (events.js:179:7)
    at endReadableNT (_stream_readable.js:913:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
From previous event:
    at Horseman.<anonymous> (/Users/jim.cummins/projects/tiyo-login/node_modules/node-horseman/lib/actions.js:914:5)
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)
From previous event:
    at Horseman.exports.evaluate (/Users/jim.cummins/projects/tiyo-login/node_modules/node-horseman/lib/actions.js:832:20)
    at Horseman.(anonymous function) [as evaluate] (/Users/jim.cummins/projects/tiyo-login/node_modules/node-horseman/lib/index.js:402:17)
    at Horseman.<anonymous> (/Users/jim.cummins/projects/tiyo-login/node_modules/node-horseman/lib/index.js:410:22)
    at /Users/jim.cummins/projects/tiyo-login/node_modules/node-phantom-simple/node-phantom-simple.js:60:18
    at IncomingMessage.<anonymous> (/Users/jim.cummins/projects/tiyo-login/node_modules/node-phantom-simple/node-phantom-simple.js:645:9)
    at emitNone (events.js:85:20)
    at IncomingMessage.emit (events.js:179:7)
    at endReadableNT (_stream_readable.js:913:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
From previous event:
    at Promise.HorsemanPromise.(anonymous function) [as evaluate] (/Users/jim.cummins/projects/tiyo-login/node_modules/node-horseman/lib/index.js:408:15)
    at login (/Users/jim.cummins/projects/tiyo-login/index.js:15:6)
    at Object.<anonymous> (/Users/jim.cummins/projects/tiyo-login/examples/as-library.js:12:1)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:148:18)
    at node.js:405:3

  horseman .close(). +92ms
Warning: a promise was rejected with a non-error: [object Object]
    at ClientRequest.<anonymous> (/Users/jim.cummins/projects/tiyo-login/node_modules/node-phantom-simple/node-phantom-simple.js:501:11)
From previous event:
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)
From previous event:
    at login (/Users/jim.cummins/projects/tiyo-login/index.js:35:13)
    at Object.<anonymous> (/Users/jim.cummins/projects/tiyo-login/examples/as-library.js:12:1)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:148:18)
    at node.js:405:3

Unhandled rejection waitForCb
evaluatePage

➜  examples git:(horsemanjs) ✗ node ./as-library.js
Unhandled rejection waitForCb
evaluatePage

global code
evaluateJavaScript@[native code]
evaluate@phantomjs://platform/webpage.js:390:39
phantomjs://code/bridge.js:121:61
    at /Users/jim.cummins/projects/tiyo-login/node_modules/node-horseman/lib/actions.js:989:36
    at tryCatcher (/Users/jim.cummins/projects/tiyo-login/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.fromNode.Promise.fromCallback (/Users/jim.cummins/projects/tiyo-login/node_modules/bluebird/js/release/promise.js:178:30)
➜  examples git:(horsemanjs) ✗ node ./as-library.js
Unhandled rejection waitForCb
evaluatePage

global code
evaluateJavaScript@[native code]
evaluate@phantomjs://platform/webpage.js:390:39
phantomjs://code/bridge.js:121:61
    at /Users/jim.cummins/projects/tiyo-login/node_modules/node-horseman/lib/actions.js:989:36
    at tryCatcher (/Users/jim.cummins/projects/tiyo-login/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.fromNode.Promise.fromCallback (/Users/jim.cummins/projects/tiyo-login/node_modules/bluebird/js/release/promise.js:178:30)
    at Horseman.<anonymous> (/Users/jim.cummins/projects/tiyo-login/node_modules/node-horseman/lib/actions.js:987:29)
    at Horseman.tryCatcher (/Users/jim.cummins/projects/tiyo-login/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/jim.cummins/projects/tiyo-login/node_modules/bluebird/js/release/promise.js:504:31)
    at Promise._settlePromise (/Users/jim.cummins/projects/tiyo-login/node_modules/bluebird/js/release/promise.js:561:18)
    at Promise._settlePromiseCtx (/Users/jim.cummins/projects/tiyo-login/node_modules/bluebird/js/release/promise.js:598:10)
    at Async._drainQueue (/Users/jim.cummins/projects/tiyo-login/node_modules/bluebird/js/release/async.js:143:12)
    at Async._drainQueues (/Users/jim.cummins/projects/tiyo-login/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/jim.cummins/projects/tiyo-login/node_modules/bluebird/js/release/async.js:17:14)
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)

```

**Comment by awlayton** [comment]
It would seem that the code for waiting for the page injection to finish does not always work. When I get time I will look into it. If you put a `.delay()` after the `.open()` does that improve/fix the problem?

**Comment by jimthedev** [comment]
@awlayton I put long delays between each step and it still happens with the same error. Doesn't seem to be timing related in this sense. It appears the page has no problem navigating between the two pages (my click causes a new page to be loaded). My wait selector is really just waiting for the new page to be drawn. 

I even put a screenshot in there after the delay but before evaluate. It runs properly and the screenshot is correct.

**Comment by jimthedev** [comment]
FWIW jQuery is already in this page so it is not getting injected.

**Comment by jimthedev** [comment]
Ok solved my issue. I was using waitForSelector when I really wanted to waitForNextPage combined with waitForSelector. Once I used both and bumped up my timeout I was able to get it to work. I think the problem is that I was evaluating before horseman was injected.

**Comment by robertpallas** [comment]
I am not able to recreate the situation playing against my test page. My theory on the issue I am having is as follows:

1. User(end user using my app that is running Horseman) initiates login on Webpage (the web that causes the reference error) via the App(Hapi powered API heavily using Horseman to interact with different sites based on user actions)
2. Webpage is waiting for the User to finish login on their mobile device with 2 factor auth
3. Once the 2 factor auth is successful Webpage _sometimes_ refreshes, other times loads the new DOM elements async. That is why I have hard time recreating it and see it in logs on some of the attempts only.
4. App constantly checks what the status is on the Webpage going to `.evaluate()` once login has been successful.

My implementation uses `.waitFor()` with a function checking if the evaluatable is readable and if it is not then repeats the request checking if auth status is waiting, done or timed out. Now the times that the webpage did refresh I dont have any way to get `onLoadFinished` to run and `__horseman` to be there before evaluate. I can not start waiting for next page at any point since the 2 factor auth could take any amount of time. Is there a way to force the `onLoadFinished` event without `.waitForNextPage()`? This would most likely be better for my case than the temporary solution in this PR.

PR itself does offer help in similar weird cases as protection but it does possibly mask some other issues.

**Comment by jimthedev** [comment]
I was able to resolve my issue without this PR.

**Comment by jorgeesquer** [comment]
I had this problem last week. The code in the PR fixed it (or hid it).

The problem occurred when I tried to run `evaluate` inside an iframe. jQuery wasn't being injected into the iframe either, though I didn't need that.

**Comment by Turboman99** [comment]
@jimthedev Did you resolve this issue by calling .waitForNextPage, followed by .waitForSelector, and bumping up the timeout in your config? Otherwise, please share!

**Comment by emmerich** [comment]
I have the same problem as @jorgeesquer .

When I call
```javascript
horseman
  .switchFrame(1)
  .evaluate(function() {
    console.log('Hello');
  })
```

I have the error: 
```
"Phantom error" [
  "ReferenceError: Can't find variable: __horseman",
  [
    {
      "file": "undefined",
      "line": 2,
      "function": "evaluate"
    },
    {
      "file": "",
      "line": 74,
      "function": ""
    }
  ]
]
```

If I include this pull request, I no longer have the error, but I also don't have jQuery injected inside the frame.

Is is possible that Horseman is not "rebuilding" the Horseman context in the frame?

Full output of commands with Horseman logs:
```
Tue, 14 Mar 2017 10:43:44 GMT horseman phantom created
Tue, 14 Mar 2017 10:43:44 GMT horseman phantom version 2.1.1
Tue, 14 Mar 2017 10:43:44 GMT horseman page created
Tue, 14 Mar 2017 10:43:44 GMT horseman phantomjs onLoadFinished triggered success NaN
Tue, 14 Mar 2017 10:43:44 GMT horseman injected jQuery from /home/steven/wars/groot/bin/groot/bin/lib/jquery-2.1.1.min.js
Tue, 14 Mar 2017 10:43:44 GMT horseman .viewport() set 1024 768
Tue, 14 Mar 2017 10:43:44 GMT horseman .on() consoleMessage set.
Tue, 14 Mar 2017 10:43:44 GMT horseman .on() error set.
Tue, 14 Mar 2017 10:43:44 GMT horseman .userAgent() set Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36
Tue, 14 Mar 2017 10:43:44 GMT horseman .url()
[Tue Mar 14 2017 11:43:44 GMT+0100 (CET)] [trace] "[ACTION][OPEN] Opening http://localhost:3009/contentInAFrame?firstFrame"
Tue, 14 Mar 2017 10:43:44 GMT horseman .open() http://localhost:3009/contentInAFrame?firstFrame
Tue, 14 Mar 2017 10:43:44 GMT horseman phantomjs onLoadFinished triggered success 1
Tue, 14 Mar 2017 10:43:44 GMT horseman injected jQuery from /home/steven/wars/groot/bin/groot/bin/lib/jquery-2.1.1.min.js
Tue, 14 Mar 2017 10:43:44 GMT horseman .url()
[Tue Mar 14 2017 11:43:44 GMT+0100 (CET)] [trace] "Opened link at http://localhost:3009/contentInAFrame?firstFrame"
[Tue Mar 14 2017 11:43:44 GMT+0100 (CET)] [trace] "Getting href from a with frame 0"
[Tue Mar 14 2017 11:43:44 GMT+0100 (CET)] [trace] "Getting links"
Tue, 14 Mar 2017 10:43:44 GMT horseman .evaluate() <anonymous> a href
Tue, 14 Mar 2017 10:43:44 GMT horseman .switchToFrame() 0
[Tue Mar 14 2017 11:43:44 GMT+0100 (CET)] [error] "Phantom error" [
  "ReferenceError: Can't find variable: __horseman",
  [
    {
      "file": "undefined",
      "line": 2,
      "function": "evaluate"
    },
    {
      "file": "",
      "line": 74,
      "function": ""
    }
  ]
]
Tue, 14 Mar 2017 10:43:44 GMT horseman .waitFor() waitForCb
{ line: 2,
  stack: 'waitForCb\nevaluatePage\n\nglobal code\nevaluateJavaScript@[native code]\nevaluate@phantomjs://platform/webpage.js:390:39\nphantomjs://code/bridge.js:121:61\n    at /home/steven/wars/groot/node_modules/node-horseman/lib/actions.js:989:36\n    at tryCatcher (/home/steven/wars/groot/node_modules/bluebird/js/release/util.js:16:23)\n    at Function.Promise.fromNode.Promise.fromCallback (/home/steven/wars/groot/node_modules/bluebird/js/release/promise.js:179:30)\n    at Horseman.<anonymous> (/home/steven/wars/groot/node_modules/node-horseman/lib/actions.js:987:29)\n    at Horseman.tryCatcher (/home/steven/wars/groot/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/home/steven/wars/groot/node_modules/bluebird/js/release/promise.js:510:31)\n    at Promise._settlePromise (/home/steven/wars/groot/node_modules/bluebird/js/release/promise.js:567:18)\n    at Promise._settlePromiseCtx (/home/steven/wars/groot/node_modules/bluebird/js/release/promise.js:604:10)\n    at Async._drainQueue (/home/steven/wars/groot/node_modules/bluebird/js/release/async.js:138:12)\n    at Async._drainQueues (/home/steven/wars/groot/node_modules/bluebird/js/release/async.js:143:10)\n    at Immediate.Async.drainQueues (/home/steven/wars/groot/node_modules/bluebird/js/release/async.js:17:14)\n    at runCallback (timers.js:666:20)\n    at tryOnImmediate (timers.js:639:5)\n    at processImmediate [as _immediateCallback] (timers.js:611:5)' }
```

**Comment by emmerich** [comment]
@awlayton I believe there's a bug relating to iframes which relates to this PR, so I've opened it up [here](https://github.com/johntitus/node-horseman/issues/268).

**Comment by awlayton** [comment]
As I said before, this is more of a bandaid than a fix for the underlying issue. However, I do not know when I will have the time to fix it properly.

I am leaning towards accepting this since it will make things *better* now, even if not *completely right*. Do you have an opinion on merging this in @johntitus?

**Comment by johntitus** [comment]
The part about jquery not being injected after this pull requests concerns me, but it looks like all tests are passing.  I'd say do it, and let's see if anyone complains.

**Comment by awlayton** [comment]
The PR won't cause jQuery to not be inject any more than before. I am not entirely happy because it won't fix whatever is already causing jQuery etc. to not get injected sometimes.

**Comment by awlayton** [comment]
I see to have confused GitHub, but the changes from this PR are merged in now.

**Pull request closed without merging**
