### PR TITLE
Added cropBase64

### PR DESCRIPTION
**Pull request by jeprojects**
This function will allow you to get a crop in base64

### CODE REVIEW

**Comment by johntitus** [comment]
Very cool! Love it when someone adds a pull request to fix an issue they raised.  But, would you mind adding a test for it? Could be very similar to the `.screenshotBase64()` test:

https://github.com/johntitus/node-horseman/blob/master/test/index.js#L621-L635

**Comment by jeprojects** [comment]
Sorry about the 2 pull requests for the same task.. I couldn't work out how to add the test to this pull request.

So the test will fail because the new method isn't found yet.

**Comment by jeprojects** [comment]
Ok worked it out and added test.

**Comment by johntitus** [comment]
Thanks!

**Pull request merged**
