### PR TITLE
fix crop with zoom set

### PR DESCRIPTION
**Pull request by wong2**
currently, node-horseman's `crop` method can't produce the correct screenshot if the page has a zoomFactor other than 1.

example code:

    var Horseman = require('node-horseman');
    var horseman = new Horseman();

    horseman
      .viewport(3200, 1800)
      .zoom(2)
      .open('https://www.google.com')
      .crop('#hplogo', 'screenshot.png')
      .close()

without this patch, would produce:

screenshot2

(yep, a white image)

with this patch, would produce:

image

### CODE REVIEW

**Comment by awlayton** [comment]
Could you add checks to reject if any of the callbacks on lines [363][], [371][], or [372][] get an error and one to reject if the Promise on line [373][] rejects?

Also, we need a test added for this test case.

[363]: https://github.com/johntitus/node-horseman/pull/92/files#diff-b4f00973447f4e140c1e582550721ec4R363
[371]: https://github.com/johntitus/node-horseman/pull/92/files#diff-b4f00973447f4e140c1e582550721ec4R371
[372]: https://github.com/johntitus/node-horseman/pull/92/files#diff-b4f00973447f4e140c1e582550721ec4R372
[373]: https://github.com/johntitus/node-horseman/pull/92/files#diff-b4f00973447f4e140c1e582550721ec4R373

**Comment by awlayton** [comment]
I forgot to mention, thanks for finding, *and* figuring out how to fix, this bug @wong2.

**Comment by wong2** [comment]
@awlayton I've added the rejects and test case

**Comment by awlayton** [comment]
The code looks good now.

The test doesn't really test if the zooming works, but now that I actually think about it I'm not sure how you could easily test that...

Also, why did you change that other test?

**Comment by wong2** [comment]
close now

**Comment by awlayton** [comment]
Why close it @wong2?

**Comment by wong2** [comment]
:beers:

**Comment by w33ble** [comment]
Oddly enough, this PR breaks zoom for me. When I set the zoom to 2, I get images that are 1/4 of their expected size. Things worked correctly in 2.x, and when I get rid of the `* zoomFactor` locally, it works again.

This is using Phantom 2.1.1, I'm not sure if 1.9.8 behaves differently or not.

**Comment by wong2** [comment]
@w33ble so it works in 2.x, and breaks in 1.x ?

**Comment by w33ble** [comment]
No, it's broken using v3.1.1 of this library and phantom v2.1.1 with a zoom level of 2. 

I haven't tried it with phantom v1.9.8.

**Comment by wong2** [comment]
@w33ble 
1. can you try to zoom the webpage you're taking screenshot to 200% in the browser, and check if the page behavior properly?
2. this feature needs to be used with a big `viewport`

**Comment by w33ble** [comment]
Yeah, it behaves correctly in a browser when zoomed in. I'm using a viewport of { width: 1950, height: 1200 }. 

It works as expected when I remove the code that multiplies the offsets by the zoom factor too. I'm not sure what's right in this instance, if it should or should not multiple by the zoom factor, but in my case, doing so breaks things. I haven't had time to investigate further, I got around the issue for now by creating a fork of this module.

**Comment by awlayton** [comment]
It sounds like there was a bug in Phantom 1.x that this PR fixed, but now the bug is fixed in Phantom 2.x and the double fixing is bad.

Hopefully all we need horseman to do is switch the behavior based on the Phantom version.

**Pull request closed without merging**
