### PR TITLE
Allow chaining off Promises

### PR DESCRIPTION
**Pull request by awlayton**
I liked the look of the API before Promises. Don't get me wrong, I like Promises.

I made the Promise API able to chain more like the old one. Hopefully you think it is nice too...

### CODE REVIEW

**Comment by bchr02** [comment]
> I liked the look of the API before Promises. 

I always thought the same thing too. Can't wait to try this! Awesome!

**Comment by bchr02** [comment]
@awlayton I was looking at your changes. This appears to keep things backwards compatible so that @johntitus wouldn't have to make this a major revision. In other words it can stay at v2. Is that correct?

**Comment by johntitus** [comment]
Very cool. Thanks @awlayton! I definitely plan to pull & release a new version with this, but probably won't get time to get into it until next week. If everything looks good, I'll rewrite the readme to make this the default way of using the API.

**Comment by awlayton** [comment]
Yes @bchr02, the changes should be backwards compatible because the actions still return real Promises.

**Comment by bchr02** [comment]
That's awsome! thanks @awlayton I'm sure a lot of other people will also appreciate this. This should also make it more backward compatible with v1 code.

**Comment by johntitus** [comment]
Thanks again @awlayton for this great pull request.  I've merged it and updated the readme & examples to make use of it.  I'll get around to rewriting the tests to use it eventually.

**Pull request merged**
