### PR TITLE
jQuery path can be specified in options.

### PR DESCRIPTION
**Pull request by emmerich**
I have added a patch to horseman to allow the jQuery location to be specified in options. By default, we still use the implementation shipped with horseman.

### CODE REVIEW

**Comment by awlayton** [comment]
I guess I am OK with this change if @johntitus likes it too. We probably need a test for it though.

**Comment by wong2** [comment]
if the user has his own jQuery, why not just use `injectJs` instead of the `injectJquery` behavior?

**Comment by awlayton** [comment]
I agree @wong2 that this is not entirely necessary. I admittedly have a tendency to add too many features "convenience" sometimes. That is why I wanted to see if @johntitus wanted this feature.

The only real advantage of this feature is not having to call `.injectJs()` several times if several pages are being opened.

**Comment by emmerich** [comment]
Would using `.injectJs()` mean you have to inject jQuery twice? Once for the built-in Horseman jQuery and once for your own? Would this cause conflicts or are the performance hits something you'd be concerned about?

The original use-case for this feature was actually that I was bundling my Horseman application in an executable bundler (`nexe`), which mangles `__dirname` a bit, so I couldn't use the default jQuery path built into Horseman.

I'm okay if you want to accept the change or not. If you'd like it let me know and I'll write some tests for it, if not I will leave a link to the commit on my fork here: https://github.com/emmerich/node-horseman/tree/e9cb669f91f9601551cb576e82d3054b4b2cc747

**Comment by awlayton** [comment]
It would not require injecting jQuery twice @emmerich. The built-in jQuery injection can be disabled, and then one can use `.injectJs()` to inject whatever jQuery they want.

I am kind of on the fence about this and it sounds like @wong2 is maybe against it. I will mull this over and see if anyone else chimes in.

Out of curiosity, is there any sort of workaround that you know of for this `nexe` stuff?

**Comment by emmerich** [comment]
I wondered if Horseman uses some jQuery functions internally, and thus disabling jQuery and injecting it at a later time might cause problems. No problem though, the `injectJs` solution seems to be a good one. I will keep my fork open until I get the chance to test using `injectJs` instead of using jQuery directly.

The problem with `nexe` is that when you try to reference a file at runtime, the `__dirname` becomes slightly mangled. They mention on their issues page that `__dirname` should consistently be the working directory but I had problems. As Horseman uses the `__dirname` to resolve the jQuery path I ran into issues locating the file.

Well, I'm babbling a bit but basically it'd require a bug fix within `nexe`. They are aware of the problem but I'm not sure of any time scales. I found it easier to change Horseman than to fix `nexe`, and thought that the change I made might appeal to you for other reasons (not sure, maybe easily changing the jQuery version or using a custom built jQuery, something like that).

**Comment by wong2** [comment]
@emmerich Horseman itself does not depend on jQuery, I always set `injectJquery` to false since the website I'm scripting already has jQuery on it, and it works fine.

**Comment by awlayton** [comment]
Yes horseman is written to use jQuery if it is there, otherwise is just uses `document.querySelector` and similar. It does not *need* jQuery @emmerich.

Also, FYI horseman will not inject jQuery if it is already present on the page. You do not need to disable it @wong2, though it won't hurt anything.

**Comment by wong2** [comment]
@awlayton yeah but set to false will reduce one `page.evaluate` call (check if has jQuery)

**Comment by emmerich** [comment]
Closing this as there are alternatives.

**Pull request closed without merging**
